spring:
  jpa:
    show-sql: true # sql ???? ??? ???? ??.
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate # ??? ?? ? ??? ???? ??? ??? ???? ? ?? (create, update ? ?? ??? ?? --> validate ??!)
  datasource:
    url: jdbc:mysql://localhost:3307/book_store?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true # mysql ?? ??
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!! # db ????